examples: Add missing return values
examples/domipaddrs.py:43: error: Missing return statement
examples/dhcpleases.py:45: error: Missing return statement

Signed-off-by: Philipp Hahn <hahn@univention.de>