python: Fix the forward_null error in Python binding codes
This patch resolves: https://bugzilla.redhat.com/show_bug.cgi?id=771021
(cherry picked from commit b80f4db9931ceea4bec1d178322058df77ece7a4)

Related coverity log:

Error: FORWARD_NULL:
/builddir/build/BUILD/libvirt-0.9.10/python/libvirt-override.c:355:
assign_zero: Assigning: "params" = 0.
/builddir/build/BUILD/libvirt-0.9.10/python/libvirt-override.c:458:
var_deref_model: Passing null variable "params" to function
"getPyVirTypedParameter", which dereferences it. (The dereference is assumed on
the basis of the 'nonnull' parameter attribute.)